# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: History of Indigenous People in Latin America 
description: > # this means to ignore newlines until "baseurl:"
       Spring 2013, University of Tennesse. Course on the History of Indigenous
       People in Latin America. It was good class, you should've enrolled.
baseurl: "2013HIST475" # the subpath of your site, e.g. /blog
url: "http://chadblack.github.io" # the base hostname & protocol for your site
twitter_username: parezcoydigo
github_username: chadblack

# Build settings
markdown: kramdown


